apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-10m-pv

spec:
  storageClassName: host-test # 与PVC的storageClassName匹配
  accessModes:
    - ReadWriteOnce # 可以被单个节点挂载为读写模式
  capacity:
    storage: 10Mi
  hostPath:
    path: /tmp/host-10m-pv # 存储在节点上的路径
