# ---------------------------------------------------------------
# daemonSet demo
# ---------------------------------------------------------------
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: redis-ds
  namespace: demo-ns
  labels:
    app: redis-ds

spec:
  selector:
    matchLabels:
      name: redis-ds

  # 更新策略
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      # 表示在更新过程中最多可以有多少个 Pod 处于不可用状态，默认为 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        name: redis-ds
    spec:
      containers:
        - name: redis
          image: redis:5-alpine
          ports:
            - containerPort: 6379

      # 容忍污点
      # tolerations:
      #   - key: node-role.kubernetes.io/control-plane
      #     effect: NoSchedule
      #     operator: Exists
