apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngx-dep
  namespace: rolling-update-demo

spec:
  minReadySeconds: 20 # 确认Pod就绪的等待时间
  replicas: 4
  selector:
    matchLabels:
      app: ngx-dep

  template:
    metadata:
      labels:
        app: ngx-dep
    spec:
      volumes:
        - name: ngx-conf-vol
          configMap:
            name: ngx-conf

      containers:
        - image: nginx:1.22-alpine222222
          name: nginx
          ports:
            - containerPort: 80

          volumeMounts:
            - name: ngx-conf-vol
              mountPath: /etc/nginx/conf.d
