# ---------------------------------------------------------------
# deployment demo
# ---------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
  namespace: demo-ns

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-dep

  # deployment 与 template 是松耦合的关系
  template:
    metadata:
      labels:
        app: nginx-dep
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "250m"

      restartPolicy: Always
