# ---------------------------------------------------------------
# 默认service 类型为 ClusterIP
# ---------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: ngx-svc
  namespace: demo-ns

spec:
  selector:
    app: ngx-dep

  ports:
    - port: 8081
      targetPort: 80
      protocol: TCP
