apiVersion: v1
kind: Service
metadata:
  name: ngx-svc-nodeport
  namespace: demo-ns

spec:
  selector:
    app: ngx-dep

  ports:
    - port: 8082
      targetPort: 80
      protocol: TCP

  type: NodePort
