apiVersion: v1
kind: ConfigMap
metadata:
  name: ngx-conf
  namespace: demo-ns

data:
  # 默认配置文件，输出服务器的地址、主机名、请求的URI等基本信息
  default.conf: |
    server {
      listen 80;
      location / {
        default_type text/plain;
        return 200
          'srv : $server_addr:$server_port\nhost: $hostname\nuri : $request_method $host $request_uri\ndate: $time_iso8601\n';
      }
    }
