# ----------------------------------------------------
# 通过环境变量的方式使用ConfigMap和Secret
# ----------------------------------------------------

apiVersion: v1
kind: Pod
metadata:
  name: use-config-env-pod
  namespace: demo-ns

spec:
  containers:
    - name: busy
      image: busybox
      imagePullPolicy: IfNotPresent

      env:
        - name: COUNT
          valueFrom:
            configMapKeyRef:
              name: config-info
              key: count

        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-info
              key: username

      command: ["/bin/sh", "-c", "echo $COUNT; echo $USERNAME; sleep 3600"]

      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "250m"
